name: Build Bicep Modules

run-name: >
  ${{ github.workflow }}: ${{ github.event_name }} for ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up Azure CLI
      uses: azure/cli@v2
      with: 
        azcliversion: latest
        inlineScript: |
          az account show
        
    - name: Install Bicep CLI
      run: |
        az bicep install
        az bicep version

    - name: Validate and Test Bicep modules
      run: |
        for dir in $(find . -type d); do
          if [ -f "$dir/main.bicep" ]; then
            param_file="$dir/params.bicepparam"
            echo "Validating $dir/main.bicep"
            az bicep build --file $dir/main.bicep
            if [ -f "$param_file" ]; then
             echo "Testing $dir/main.bicep with parameters $param_file"
              az deployment group validate --resource-group rg-bicepbuild-dev-001 --template-file $dir/main.bicep --parameters $param_file
            else
              echo "Testing $dir/main.bicep without parameters"
              az deployment group validate --resource-group rg-bicepbuild-dev-001 --template-file $dir/main.bicep
            fi
          fi
        done

#     - name: Test Azure Well-Architected Framework (PSRule)
#       uses: Microsoft/ps-rule@v2.9.0
#       with:
#         modules: PSRule.Rules.Azure