name: Bicep Validation and Publish

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bicep Build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: main.bicep
          outputFilePath: azuredeploy.json

  publish:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Bicep files to ACR
        env:
          ACR_NAME: youracrname
          ACR_REPO: bicepmodules
        run: |
          az acr login --name $ACR_NAME
          for file in $(find . -name '*.bicep'); do
            module_name=$(basename $file .bicep)
            echo "Building $file"
            bicep build $file
            echo "Pushing $module_name to ACR"
            az acr repository upload --name $ACR_NAME --image $ACR_REPO/$module_name:v1 --source ./$(dirname $file)/$module_name.json
          done
