name: Publish Bicep Modules 

run-name: >
  ${{ github.workflow }}: ${{ github.event_name }} for ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      module_name:
        description: 'The module name to publish'
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up Azure CLI
      uses: azure/cli@v2
      with: 
        azcliversion: latest
        inlineScript: |
          az account show
        
    - name: Install Bicep CLI
      run: |
        az bicep install
        az bicep version

    - name: Validate and Test Bicep module
      run: |
        module_name="${{ github.event.inputs.module_name }}"
        module_dir=$(find . -type d -name "$module_name" -print -quit)
        if [ -f "$module_dir/main.bicep" ]; then
          param_file="$module_dir/params.bicepparam"
          echo "Validating $module_dir/main.bicep"
          az bicep build --file $module_dir/main.bicep
          if [ -f "$param_file" ]; then
            echo "Testing $module_dir/main.bicep with parameters $param_file"
            az deployment group validate --resource-group rg-bicepbuild-dev-001 --template-file $module_dir/main.bicep --parameters $param_file
          else
            echo "Testing $module_dir/main.bicep without parameters"
            az deployment group validate --resource-group rg-bicepbuild-dev-001 --template-file $module_dir/main.bicep
          fi
        else
          echo "Module $module_dir/main.bicep does not exist"
          exit 1
        fi

  Publish:
    runs-on: ubuntu-latest
    needs: Build
    environment: public
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up Azure CLI
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
        
    - name: Install Bicep CLI
      run: |
        az bicep install
        az bicep version
      
    - name: Extract version from metadata
      id: version
      run: |
        module_name="${{ github.event.inputs.module_name }}"
        module_dir=$(find . -type d -name "$module_name" -print -quit)
        if [ -f "$module_dir/metadata.json" ]; then
          version=$(jq -r '.version' "$module_dir/metadata.json")
          echo "::set-output name=version::$version"
        else
          echo "metadata.json not found in $module_dir"
          exit 1
        fi

    - name: Publish Bicep modules
      run: |
        module_name="${{ github.event.inputs.module_name }}"
        module_dir=$(find . -type d -name "$module_name" -print -quit)
        parent_dir=$(dirname "$module_dir")
        parent_dir=$(basename "$parent_dir")
        version="${{ steps.version.outputs.version }}"
        if [ -f "$module_dir/main.bicep" ]; then
          registry="br:latzo.azurecr.io/bicep/modules/$parent_dir/$module_name"

          # Publish version
          echo "Publishing $module_dir/main.bicep to $registry:$version"
          az bicep publish --file $module_dir/main.bicep --target $registry:$version
          
        else
          echo "Module $module_dir/main.bicep does not exist"
          exit 1
        fi